### ISSUE TITLE
Proper config for cold dark [pictures] 

### ISSUE THREAD

**Issue by Zyonix007** [wpine215/msfs-a320neo#179]
![Microsoft Flight Simulator Screenshot 2020 08 28 - 00 47 08 74](https://user-images.githubusercontent.com/60050366/91522394-1ca68600-e8c8-11ea-8117-b1f647adf459.png)
![Microsoft Flight Simulator Screenshot 2020 08 28 - 00 47 18 99](https://user-images.githubusercontent.com/60050366/91522398-1f08e000-e8c8-11ea-9e89-39f1e9eaea4e.png)
![Microsoft Flight Simulator Screenshot 2020 08 28 - 00 47 23 11](https://user-images.githubusercontent.com/60050366/91522403-203a0d00-e8c8-11ea-8944-e6b306030cef.png)

**Comment by becas22** [comment]
A few observations:

- I would leave temperature selectors at 12 o'clock;

- ACP 3 should have PA selected and volume above 1 o'clock;

- EFIS Control Panel should be in ARC or NAV, not LS;

- MULTISCAN and GCS should be on AUTO;

- I would put the mode in WX+T and Tilt at +4º;

- ATC ALT RPTG should be ON;

- TCAS should be on STBY;

- Loudspeaker should be at 1 o'clock.

**Comment by JackZ974** [comment]
Some things depend on the state the previous crex left the A/C. Do not forget the AUDIO SWITCHING that should be on NORM

**Comment by AdenFlorian** [comment]
> TCAS should be on STBY;
@becas22 are you talking about the STBY/AUTO/ON switch or the STBY/TA/TA/RA switch?

If talking about the STBY/TA/TA/RA switch, do you know what the STBY/AUTO/ON switch should be set to when starting cold and dark?

**Comment by Zyonix007** [comment]
It should be standby

**Comment by JackZ974** [comment]
The ATC button should be set on STBY, so that it doesn't inadvertently triggers an alarm on the Airport Ground Radar in case the plane is moved by maintenance during the night and turned on later on.
As an extra safety measure, the last code set on the XPDR should also be a discrete one (usually 2000 in Europe, dunno about the US), before turning it to STBY, in order to avoid duplicate XPDER codes events upon startup. 

I think that left in the AUTO position the A/C only operates in "limited" mode S only(selective interrogation mode) while on ground, in order to avoid to trigger TCAS warnings with other aircraft in flight approaching the closest runway. In that mode and on the ground, thanks to a weight on wheell ("On the ground" status) it will basically only appear on Ground Airports Radars  and not on other TCASes.

So the risk is limited to let it on AUTO, that's the reason we never set the ATC to ON in flight in order not to forget it while on the ground and let the AIrbus .

**Comment by AdenFlorian** [comment]
might want to get some updated pictures from the `dev-0.1.1`

**Comment by Zyonix007** [comment]
The latest dev branch is correct

**Comment by AdenFlorian** [comment]
so this issue should be closed then?

**Comment by Zyonix007** [comment]
Yes
