### ISSUE TITLE
Battery Voltage does not change anymore

### ISSUE THREAD

**Issue by DoToAdventures** [wpine215/msfs-a320neo#261]
After updating to the latest devbranch the voltage indicators for the batteries do not work anymore.
The behaviour I observed before was a change from 25.4V to 28.4V when ext power is turned on, this is not present anymore. I believe the cause of this issue is Pull request #249 
I observed a stream in the discord where this also occured, should be 100% reproducable.
https://i.imgur.com/m4PKWhv.png

**Comment by ThePilot916** [comment]
This has been changed intentionally,, according to IRL Pilots, the ovhd battery voltage displays true battery voltage but asobo's implementation has all buses connected disregarding for type of current, the voltage increased previously on the main bus from 25.4 to 28.4 as a function of APU N% and the battery voltage display read the voltage from the main bus instead of the batteries.

- This will get fixed once we finish modelling electrical system(the existing logic implemented by asobo is wrong)

Also a reason why its in the dev build, we cannot keep updating minute details(it can be corrected with one simvar change but it'll be with a wrong logic) until the very underlying systems are not even implemented.

**Comment by DoToAdventures** [comment]
Roger! All good if it's intentional.
