### ISSUE TITLE
Remove "60" callout from landing annunciations

### ISSUE THREAD

**Issue by michaeldiguiseppi** [wpine215/msfs-a320neo#86]
The real A320 calls out 100...50...40...30...20...5. Remove 60.

**Comment by michaeldiguiseppi** [comment]
Reopening (for new sounds branch)

**Comment by Alexr03** [comment]
After further investigating, to do what this PR describes we only need to edit the panel.xml to remove the callout sound. We do not need to mess with the sounds.xml. 

@michaeldiguiseppi Would you prefer me to do another PR with the only change being in the panel.xml, i've verified this doesn't remove all plane sounds, but only the callout. Or we can investigate further into the sounds.

**Comment by Alexr03** [comment]
Little further digging...
I can modify the sounds.xml and get aircraft sounds to function, but you also need to include "Asobo_A320_NEO.PC.PCK" in the sound directory along with the xml file. Which does make sense, since if in the future of this project we are manipulating the sounds, we need to give it this new PCK file anyway.

No idea why that if we don't provide this and define it in the layout it wont use the default PCK in the Official directory though.

**Comment by michaeldiguiseppi** [comment]
Merged into branch: sound-mods for further research/manipulation of sounds.
